spring:
  datasource:
    url: jdbc:mysql://localhost:3306/advertisement_jvm
    username: testUser
    password: testUser
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
