spring:
  datasource:
    url: jdbc:mysql://localhost:3306/advertisement_jvm
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
